### ISSUE TITLE
Support cool and interactive animations/transitions with MotionLayout

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/Covid19-Notifier-IN#33]
### Proposed change
- Support for some cool, interactive animations/transitions using `MotionLayout`.
- This change is encouraged during ***"Hacktoberfest"*** for the participants of this event.

### References
- https://medium.com/google-developers/introduction-to-motionlayout-part-i-29208674b10d
- https://developer.android.com/training/constraint-layout/motionlayout

**Comment by larissayasin** [comment]
I can add some animations. What kind of animations are you thinking?

**Comment by PatilShreyas** [comment]
@larissayasin Any type of animation. For e.g. Opening State stats, scrolling list, loading list, etc.

**Comment by larissayasin** [comment]
Hey, I'm sorry but I didn't have the time to push the code. I tried a few things but I didn't like the result, also I found a some problems with Motion Layout.

**Comment by PatilShreyas** [comment]
No problem.
